meta_product_name: "Brain-Ai-Hack"
meta_title: "Brain-Ai-Hack - Brain Ai Hack permet de créer des multi-prompts AI et de les relier pour créer des mindmaps."
meta_description: "Brain Ai Hack révolutionne la manière dont vous interagissez avec l'intelligence artificielle,
       en vous permettant de créer des mindmaps visuelles et intelligentes en toute simplicité.
       Découvrez une nouvelle dimension de la créativité, où vos idées prennent vie et
       sont organisées visuellement, tout en interrogeant plusieurs IA en même temps."
meta_image: "cover.png"
twitter_account: "@BrainAiHack"
